### ISSUE TITLE
License for code?

### ISSUE THREAD

**Issue by arfoll** [mlsorensen/SI7021#1]
Hi @mlsorensen, could you clarify the license on your code? Cheers,
Brendan

**Comment by mlsorensen** [comment]
I haven't really decided, honestly. Will probably go with a GPL variant.

**Comment by tbowmo** [comment]
Any news on the license details?

**Comment by mlsorensen** [comment]
I've just updated, GPLv2.

**Comment by josmad** [comment]
@mlsorensen Any chance that you would consider releasing under LGPL instead of GPL? Currently your library is hard to use due to the infectiveness of the GNU GPL.

**Comment by mlsorensen** [comment]
So be it.
